DATASET:
  AUGMENT: DINOv2Augmentation
  OOD_SELECTED_LABELS: null
  SELECTED_LABELS:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  TEST: cityscapes
  TRAIN: cityscapes
  VAL: cityscapes
EXPERIMENT:
  EPOCHS: 1
  EVAL_INTERVAL: 1
  EVAL_METRIC: SegmEvaluator
  NAME: grood_logml_1000K_01adamw_tau10_resetthr1
  OUT_DIR: ./
  RECOMPUTE_NM: true
  RESUME_CHECKPOINT: null
  SKIP_EPOCHS: true
  USE_EVAL_METRIC_FOR_CHCK: true
INPUT:
  BATCH_SIZE: 4
  IMG_SIZE: 1792
  IMG_TRAIN_COLOR_AUG:
  - 0.2
  - 0.2
  - 0.2
  - 0.2
  NORM_MEAN:
  - 0.485
  - 0.456
  - 0.406
  NORM_STD:
  - 0.229
  - 0.224
  - 0.225
  RANDOMCROP_AUG: false
LOSS:
  IGNORE_LABEL: 255
  TYPE:
  - CrossEntropyLoss
  WEIGHTS:
  - 1.0
MODEL:
  BACKBONE_EXP_DIR: ./_out/experiments/backbone_lp/
  EMB_SIZE: 1024
  FEATURE_RESIZE_FACTOR: 1
  FILENAME: grood
  FINETUNE: false
  INIT_TAU: 10
  MAHALANOBIS_DIST: false
  MAX_K: 1000
  MIXUP: false
  NET: GROODNetKNMSoftMultiClass
  NUM_CLASSES: 19
  PATCH_MAJORITY_VOTE_THR: 0.9
  PATCH_SIZE: 14
  RESET_ASSIGNMENT_THR: 1.0
  TAU_NORM: false
OPTIMIZER:
  CLIP_GRAD: -1.0
  LR: 0.1
  METHOD: adamw
  MOMENTUM: 0.9
  NESTEROV: false
  SCHEDULER: none
  WEIGHT_DECAY: 0.0005
SYSTEM:
  GPU_IDS:
  - 0
  NUM_CPU: 4
  RNG_SEED: 42
  USE_GPU: true
