SYSTEM:
    RNG_SEED: 42

MODEL:
    FILENAME: grood                   # net/models/ file name
    NET: GROODNetKNMSoftMultiClass
    EMB_SIZE: 1024                   # for the largest model variant
    PATCH_SIZE: 14
    NUM_CLASSES: 19                 # number of output classes
    BACKBONE_EXP_DIR: ./_out/experiments/backbone_lp/

    MAHALANOBIS_DIST: false
    MIXUP: false
    PATCH_MAJORITY_VOTE_THR: 0.9
    MAX_K: 1000
    INIT_TAU: 10 
    TAU_NORM: False
    RESET_ASSIGNMENT_THR: 1.0
    PDF_DIST2NP: False

    KNN_TYPE: condensation
    KNN_REINIT: True

LOSS: 
    TYPE: [CrossEntropyLoss] 
    WEIGHTS: [1.0]

DATASET:
    TRAIN: cityscapes
    VAL: cityscapes
    TEST: cityscapes
    AUGMENT: DINOv2Augmentation

INPUT:
    BATCH_SIZE: 4 
    IMG_SIZE: 1792                        # either list to force exact size or int for longest side size while keeping aspect ratio (as close as possible) 
    NORM_MEAN: [0.485, 0.456, 0.406]      # default IMAGENET normalization
    NORM_STD: [0.229, 0.224, 0.225]       # default IMAGENET normalization
    IMG_TRAIN_COLOR_AUG: [0.2, 0.2, 0.2, 0.2]
    RANDOMCROP_AUG: false

EXPERIMENT:
    OUT_DIR: None
    EPOCHS: 1 
    SKIP_EPOCHS: true
    EVAL_INTERVAL: 1
    EVAL_METRIC: SegmEvaluator
    USE_EVAL_METRIC_FOR_CHCK: True            

OPTIMIZER:
    METHOD: "adamw"
    LR: 0.1
    SCHEDULER: "none"

